# Generated by Django 4.1.1 on 2023-05-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'sports'},
        ),
    ]
