# Generated by Django 4.1.1 on 2023-05-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0002_alter_content_options_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detail',
            new_name='detailp',
        ),
    ]
