# Generated by Django 4.1.1 on 2023-05-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0004_alter_detailp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
