# Generated by Django 4.1.1 on 2023-05-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailho',
            options={'verbose_name': 'detailhome'},
        ),
    ]
