# Generated by Django 4.2.2 on 2023-06-26 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'home'},
        ),
        migrations.AlterModelOptions(
            name='detailho',
            options={'verbose_name': 'detailhome'},
        ),
    ]
