# Generated by Django 4.1.1 on 2023-05-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_content_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailho',
            options={'verbose_name': 'detailhome'},
        ),
    ]
