# Generated by Django 4.1.1 on 2023-05-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_detailho_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailho',
            options={'verbose_name': 'Detailho'},
        ),
    ]
