# Generated by Django 4.1.1 on 2023-05-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_detailho_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detailho',
            new_name='Detailhome',
        ),
    ]
