# Generated by Django 4.1.1 on 2023-05-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_detailhome_detailho_alter_detailho_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
    ]
