# Generated by Django 4.1.1 on 2023-04-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_detailh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailh',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
