# Generated by Django 4.1.1 on 2023-04-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_detailh_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': ' health'},
        ),
        migrations.AlterModelOptions(
            name='detailh',
            options={'verbose_name': 'detailh'},
        ),
    ]
