# Generated by Django 4.1.1 on 2023-05-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_content_options_alter_detailh_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailh',
            options={},
        ),
    ]
